# Generated by Django 5.2.4 on 2025-07-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0002_alter_comment_created_time_alter_issue_created_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
