# Generated by Django 5.2.4 on 2025-08-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0004_remove_project_code_comment_author_issue_assignee_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributors",
                to="project.project",
            ),
        ),
    ]
